Test that PNlib v2.2 has 93/90 simulating/verifying models

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -55,6 +55,16 @@ jobs:
         run: |
           python .github/scripts/archiveResults.py "PNlib" "2.2.0" "${{ matrix.omc-version }}" "html/"
 
+      - name: Verify that overview.html contains simulation and verification
+        shell: bash
+        run: |
+          if ! grep -q "<tr><td><a href=\"omc-stable/PNlib_2.2.0/PNlib_2.2.0.html\">omc-stable</a></td><td><a>93</a></td><td><a>93</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>91</a></td><td><a>90</a></td></tr></table>" overview.html; then
+            echo "Failed to find 93 simulating and 90 verifying models in overwiew.html:"
+            cat overview.html
+            exit 1
+          fi
+
+
       - name: Archive sqlite3.db
         uses: actions/upload-artifact@v4
         if: always()
