Windows support (#58)
* partial windows integration

windows integration has been added for basic operations to be executed
in local on windows os (tested on Win11 pro).

not included:
- FMI
- Docker

* help added to some arguments

* Adding windows-latest to CI

* Better default value for libraries

* Updating sanity check


---------

Co-authored-by: AnHeuermann <38031952+AnHeuermann@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,9 +12,15 @@ jobs:
     name: GitHub Actions Test
     strategy:
       matrix:
+        os: [ubuntu-latest, windows-latest]
         omc-version: [stable, nightly]
         python-version: ['3.10']
-    runs-on: ubuntu-latest
+        include:
+          - os: windows-latest
+            omc-version: stable
+            msysEnvironment: --msysEnvironment=mingw64
+      fail-fast: false
+    runs-on: ${{ matrix.os }}
     timeout-minutes: 30
 
     steps:
@@ -29,7 +35,7 @@ jobs:
             'omc'
           libraries: |
             'Modelica 4.0.0'
-            'PNlib 2.2.0'
+            'PNlib 3.0.0'
           omc-diff: true
 
       - name: Setup Python3
@@ -44,7 +50,8 @@ jobs:
 
       - name: Run library test
         shell: bash
-        run: python test.py --branch="${{ matrix.omc-version }}" --noclean --verbose configs/sanityCheck.json
+        run: |
+          python test.py --branch="${{ matrix.omc-version }}" --noclean --verbose ${{ matrix.msysEnvironment }} configs/sanityCheck.json
 
       - name: Generate HTML results
         shell: bash
@@ -53,13 +60,13 @@ jobs:
       - name: Zip HTML results
         shell: bash
         run: |
-          python .github/scripts/archiveResults.py "PNlib" "2.2.0" "${{ matrix.omc-version }}" "html/"
+          python .github/scripts/archiveResults.py "PNlib" "3.0.0" "${{ matrix.omc-version }}" "html/"
 
       - name: Verify that overview.html contains simulation and verification
         shell: bash
         run: |
-          if ! grep -q "<tr><td><a href=\"${{ matrix.omc-version }}/PNlib_2.2.0/PNlib_2.2.0.html\">${{ matrix.omc-version }}</a></td><td><a>93</a></td><td><a>93</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>91</a></td><td><a>90</a></td></tr></table>" overview.html; then
-            echo "Failed to find 93 simulating and 90 verifying models in overwiew.html:"
+          if ! grep -q "<tr><td><a href=\"${{ matrix.omc-version }}/PNlib_3.0.0/PNlib_3.0.0.html\">${{ matrix.omc-version }}</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td><td><a>92</a></td></tr></table>" overview.html; then
+            echo "Failed to find 92 simulating and 92 verifying models in overwiew.html:"
             cat overview.html
             exit 1
           fi
@@ -68,7 +75,7 @@ jobs:
         uses: actions/upload-artifact@v4
         if: always()
         with:
-          name: ${{ matrix.omc-version }}-sqlite3.db
+          name: ${{ matrix.os }}-${{ matrix.omc-version }}-sqlite3.db
           path: |
             sqlite3.db
 
@@ -76,5 +83,5 @@ jobs:
         uses: actions/upload-artifact@v4
         if: always()
         with:
-          name: ${{ matrix.omc-version }}-PNlib.html
+          name: ${{ matrix.os }}-${{ matrix.omc-version }}-PNlib.html
           path: html/
